on: [pull_request]
name: Benchmarks
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Cache cargo
        uses: actions/cache@v2.1.4
        with:
          path: |
            target
            ~/.cargo/git
            ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: smrpn/criterion-compare-action@move_to_actions 
        with:
          cwd: benches
          token: ${{ secrets.GITHUB_TOKEN }}
        

      - name: Save PR number
        run: |
            mkdir -p ./pr
            echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
            name: pr
            path: pr/

